---
- name: Setup PostgreSQL server
  # Run this playbook or tasks on servers inside the dbservers group.
  hosts: dbservers
  #Run commands with sudo (root privileges. beacause we need to install packages and manage services
  become: yes
  # These variables can be used later in tasks.
  # Example: CREATE DATABASE {{ db_name }};
  vars:
    db_name: myapp_db 
    db_user: myapp_user
    db_password: "myapp_user"

  # Tasks to be executed on the target servers.
  # This begins a list of tasks.
  # A task = one action executed on the server.Example install packages, start service, create user, create database etc
  tasks:
  # name is a description of the task. It helps to understand what the task does when you run the playbook.
    - name: Update apt cache
    # uses Ansible apt module
    # equivalent to sudo apt update on the server
    # package list must be refreshed before installing new packages to ensure we get the latest versions.
      apt:
        update_cache: yes
    

    - name: Install PostgreSQL, Python dependencies, and ACL
      apt:
        name: 
          - postgresql
          - python3-psycopg2
          - acl
        # state: present means the package should be installed. If it's already installed, it will do nothing. If it's not installed, it will install it.
        state: present

    - name: Ensure PostgreSQL service is running
    # service module is used to manage services on the server. It can start, stop, restart, enable or disable services.
    # this control system services.
    # equivalent to sudo systemctl start postgresql and sudo systemctl enable postgresql on the server.
      service:
        name: postgresql
        # start service if it's not running. If it's already running, it will do nothing.
        state: started
        # enable service to start on boot. If it's already enabled, it will do nothing.
        enabled: yes

    - name: Create PostgreSQL database
    # become postgres user to run database commands because PostgreSQL commands must be run as the postgres user.
      become: yes
      become_user: postgres
      # This tells Ansible to use the PostgreSQL database module from the community.postgresql collection.    
      # Use a module that knows how to talk to PostgreSQL instead of running raw SQL commands. This is more efficient and idempotent.
      # Ansible communicates with PostgreSQL internally using Python database libraries.
      # must install this collection:
      # ansible-galaxy collection install community.postgresql
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create PostgreSQL database user
      become: yes
      become_user: postgres
    # equivalent to running SQL commands: CREATE USER myapp_user WITH PASSWORD 'myapp_user'; 
    # this module is for managing PostgreSQL users. It can create, modify or delete users.
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present

    - name: Grant Database level privileges to user
      become: yes
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: "{{ db_name }}"
        privs: ALL
        type: database
        objs: "{{ db_name }}"
        roles: "{{ db_user }}"
        state: present

    - name: Grant Schema level privileges to user
      become: yes
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: "{{ db_name }}"
        privs: "USAGE,CREATE"
        type: schema
        objs: public
        roles: "{{ db_user }}"
        state: present
    
    - name: Grant Table level privileges to user
      become: yes
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: "{{ db_name }}"
        privs: "INSERT,SELECT,UPDATE,DELETE"
        type: table
        objs: ALL_IN_SCHEMA
        schema: public
        roles: "{{ db_user }}"
        state: present

    # above task only grants privileges on existing tables. 
    #To ensure the user has privileges on future tables, we need to set default privileges.
    - name: GRANT default privileges to user for future tables
      become: yes
      become_user: postgres
      community.postgresql.postgresql_privs:
        db: "{{ db_name }}"
        objs: TABLES
        privs: "INSERT,SELECT,UPDATE,DELETE"
        type: default_privs
        schema: public
        roles: "{{ db_user }}"
        target_roles: postgres
        state: present


        
