server_username: frontend-nextjs-user
repo_name: myabroadfriend
deploy_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIYFLC3AfdbFSKe2ff/QEGH+ntMmjLhL+ERjYVWQf0Un samir-maharjan@gmail.com"
nvm_dir: "/home/{{ server_username }}/.nvm"
node_version: "20.9.0"



