---
#Step1 Ensure the user exists
- name: Ensure the user exists
  ansible.builtin.user: 
    name: "{{ app_user }}"
    shell: /bin/bash
    create_home: yes
    state: present

#step2 Ensure the home directory exists
#double check to ensure the environment
#We are guaranteed that directory exists permissions 0755 and ownership hasnot drifted. even accidental changes had happen
- name: Ensure the home directory exists
  ansible.builtin.file:
    path: "/home/{{ app_user }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

#step 3: create the repo folder inside home of that user
- name: Create app directory for deployment
  ansible.builtin.file:
    path: "/home/{{ app_user }}/{{ repo_name }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

#step 4: create an .ssh directory
- name: Create an .ssh directory
  ansible.builtin.file:
    path: "/home/{{ app_user }}/.ssh"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0700'
    
#step 5: Set Authorized_keys so the runner can have passwordless ssh connection
#anyone who holds the private key is allowed to act as the app_user
- name: deploy key to authorized keys 
  ansible.builtin.authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ deploy_key }}"









