#list of servers
[dbservers]
#server1-ip ansible_user=ubuntu 
#forexample
192.168.122.10 ansible_user=samir-maharjan
#ansible_user is SSH username to connect to the server

[webservers]
#server2-ip ansible_user=username_of_server2
192.168.122.10 ansible_user=samir-maharjan
