#install acl package for privilege escalation and permission management
- name: Install ACL package for privilege escalation and permission management
  ansible.builtin.apt:
    name: acl
    state: present
    update_cache: yes


#this installs toolbox requied to download NVM 
#ensure various node.js and various packages can be compiled and secured on the system
- name: INSTALL dependencies for nvm
  apt:
    name:
      - curl
      - build-essential
      - libssl-dev
    state: present
    update_cache: yes

# creates tells ansible if the file already exist skip the task. NVM only gets insatlled if its isnot alredy there
- name: Install NVM
  become_user: "{{ app_user }}"
  shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ nvm_dir }}/nvm.sh"

# Install nodejs via nvm
# sourcing nvm.sh path so nvm gets known and node can be installed
- name: Install Node.js via nvm
  become_user: "{{ app_user }}"
  shell: |
    export NVM_DIR="{{ nvm_dir }}"
    [ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"
    nvm install {{ node_version }}
    nvm alias default {{ node_version }}
  args:
    executable: /bin/bash
    creates: "{{ nvm_dir }}/versions/node/v{{ node_version }}"
